# Generated by Django 5.0.6 on 2025-10-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('ccourse', models.CharField(max_length=100)),
                ('csubjects', models.CharField(max_length=100)),
                ('clocation', models.CharField(max_length=100)),
            ],
        ),
    ]
